[default]
description = "Default permissions for the system-theme plugin"
permissions = [
    "allow-get-color-scheme-preference",
    "allow-set-color-scheme-preference",
    "allow-override-system-bars-color-scheme",
]
